const sampleposts=[
    {
      "title": "Morning Yoga Session",
      "image":{
        filename:"postimage",
        url:"https://media.istockphoto.com/id/1452109215/photo/young-man-cancer-survivor-practicing-home-workout-yoga-training-stretching-muscles-and.webp?b=1&s=170667a&w=0&k=20&c=HrQbgY5RNtVY2jfXzTDyAmEmv5Ap3YHpGvBNwBXsS3I=",
      },
        "location": "San Francisco",
      "country": "United States",
      "caption": "Starting the day with a peaceful yoga session in the beautiful San Francisco park.",
      "created_at": new Date(),
    },
    {
      "title": "Artistic Studio Work",
      "image":{
        filename:"postimage",
        url: "https://images.unsplash.com/photo-1658314756129-5b27f344b65b?q=80&w=1472&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      },
      "location": "Paris",
      "country": "France",
      "caption": "An artist focuses on their masterpiece in a cozy Parisian studio.",
      "created_at": new Date(),
    },
    {
      "title": "Street Musician Performance",
      "image":{filename:"postimage",
        url:"https://images.unsplash.com/photo-1593697725250-6a184f4e9ed0?q=80&w=1374&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      },
      "location": "New York",
      "country": "United States",
      "caption": "A street musician captivates passersby with a soulful performance in New York City.",
      "created_at": new Date(),
    },
    {
      "title": "Café Catch-Up",
      "image":{filename:"postimage",
        url:"https://plus.unsplash.com/premium_photo-1661456103913-8988b2e34769?q=80&w=1632&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      },
      "location": "Rome",
      "country": "Italy",
      "caption": "Friends enjoy a lively conversation over coffee at a charming Roman café.",
      "created_at": new Date(),
    },
    {
      "title": "Market Stroll",
      "image":{filename:"postimage",
        url:"https://plus.unsplash.com/premium_photo-1686878943396-3e81cbc9b9d0?q=80&w=1374&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      },
      "location": "Tokyo",
      "country": "Japan",
      "caption": "Exploring the vibrant and bustling markets of Tokyo.",
      "created_at": new Date(),
    },
    {
      "title": "Beach Volleyball Fun",
      "image":{filename:"postimage",
        url:"https://images.unsplash.com/photo-1562552052-f6dda78e2a4d?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8ZnJpZW5kcyUyMHBsYXklMjB2b2xsZXliYWxsJTIwaW4lMjBiZWFjaHxlbnwwfHwwfHx8MA%3D%3D",
       },
        "location": "Sydney",
      "country": "Australia",
      "caption": "A group of friends playing beach volleyball under the Sydney sun.",
      "created_at": new Date(),
    },
    {
      "title": "Cultural Festival",
      "image":{filename:"postimage",
      url:"https://images.unsplash.com/photo-1541190990694-4a612732721c?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      },
      "location": "Mumbai",
      "country": "India",
      "caption": "Participants dress in colorful attire to celebrate a lively cultural festival in Mumbai.",
      "created_at": new Date(),
    },
    {
      "title": "Cityscape Photography",
      "image":{filename:"postimage",
        url:"https://images.unsplash.com/photo-1516900557549-41557d405adf?q=80&w=1528&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      },
      "location": "Hong Kong",
      "country": "Hong Kong",
      "caption": "Capturing the stunning cityscape of Hong Kong from a rooftop vantage point.",
      "created_at": new Date(),
    },
    {
      "title": "Countryside Relaxation",
      "image":{filename:"postimage",
        url:"https://plus.unsplash.com/premium_photo-1661668287291-3a7c5a5a2a6f?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      },
      "location": "Amsterdam",
      "country": "Netherlands",
      "caption": "Relaxing by a picturesque canal in the serene countryside near Amsterdam.",
      "created_at": new Date(),
    },
    
    {
      "title": "Traditional Cooking Class",
      "image":{filename:"postimage",
        url:"https://images.unsplash.com/photo-1556911073-38141963c9e0?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      },
      "location": "Mexico City",
      "country": "Mexico",
      "caption": "Learning to cook traditional Mexican dishes in a lively cooking class.",
      "created_at": new Date(),
    },
    {
      "title": "Historic Monument Visit",
      "image":{filename:"postimage",
        url:"https://plus.unsplash.com/premium_photo-1664300778169-8a45bfad23be?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      },
      "location": "Athens",
      "country": "Greece",
      "caption": "Exploring the ancient ruins of Athens and immersing in its rich history.",
      "created_at": new Date(),
    },
    {
      "title": "Winter Sports Adventure",
      "image":{filename:"postimage",
        url:"https://images.unsplash.com/photo-1488580923008-6f98dfbd7a25?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      },
      "location": "Zurich",
      "country": "Switzerland",
      "caption": "Enjoying thrilling winter sports and snowy landscapes in Zurich.",
      "created_at": new Date(),
    }
  ];
  module.exports={data:sampleposts};
  
